/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pat;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import static jdk.nashorn.internal.objects.NativeArray.pop;

/**
 *
 * @author Jacob Sacks
 */
public class NewSession extends javax.swing.JFrame {

    connectDB db = new connectDB();//creates an object for the class: connectDB
    patArray ptn = new patArray();//creates an object for the class: patArray
    sessionArray ssn = new sessionArray();//creates an object for the class: sessionArray
    Date DATE = new Date();//creates an object for the class: Date
    Validate val = new Validate();//creates an object for the class: Validate
    populateCombo pop = new populateCombo();//creates an object for the class: populateCombo
    sqlStatements sql = new sqlStatements();//creates an object for the class: sqlStatements

    /**
     * Creates new form NewSession
     */
    public NewSession() {//constructor methood for NewSession Class
        initComponents();//initiates all the components for the screen
        java.util.Date date1 = null;//creates a date varaiable that stores a date 
        DefaultComboBoxModel FNames = new DefaultComboBoxModel(pop.populateName());//Declare a Default Combo Box Model inoreder to populate a combobox
        this.cmbName.setModel(FNames);//sets the combo box to the model created above
        DefaultComboBoxModel SNames = new DefaultComboBoxModel(pop.populateSName());//Declare a Default Combo Box Model inoreder to populate a combobox
        this.cmbSname.setModel(SNames);//sets the combo box to the model created above
        if (viewSession.update == true) {//if the static variable update is set to be true
            session s = ssn.getFullSession(viewSession.currentID);//creates a new session object
            patient p = ptn.getFULLPatientID(s.getPatID());//creates a new patient object
            this.lblHead.setText("Update Session");//sets the text of the lable
            this.cmbName.setSelectedItem(p.getfName());//sets the text of the lable
            this.cmbSname.setSelectedItem(p.getsName());//sets the text of the lable
            this.cmbMin.setSelectedItem(s.getTime());//sets the text of the lable
            this.cmbHour.setSelectedItem(s.getTime().substring(0, 2));//sets the text of the lable
            this.txtIDC.setText(s.getIDC10());//sets the text of the lable
            this.txtCode.setText(s.getcode());//sets the text of the lable
            this.txtCost.setText(s.getAmount() + "");//sets the text of the lable
            String sDate1 = s.getDate();//sets the date varaible
            try {
                date1=new SimpleDateFormat("dd/MM/yyyy").parse(sDate1);//formats the date varable
            } catch (ParseException ex) {//catches the formating
                Logger.getLogger(NewSession.class.getName()).log(Level.SEVERE, null, ex);//creates the execption
            }
            this.dateCmb.setDate(date1);//sets the text of the lable
        }
        this.cmbHour.setSelectedIndex(0);//sets the text of the lable
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHead = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtIDC = new javax.swing.JTextField();
        txtCode = new javax.swing.JTextField();
        btnAddSession = new javax.swing.JButton();
        dateCmb = new com.toedter.calendar.JDateChooser();
        cmbName = new javax.swing.JComboBox<>();
        cmbSname = new javax.swing.JComboBox<>();
        btnBack = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtCost = new javax.swing.JTextField();
        cmbHour = new javax.swing.JComboBox<>();
        cmbMin = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblHead.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblHead.setText("Add a New Session");

        jLabel2.setText("Patient First Name");

        jLabel3.setText("Patient Surname");

        jLabel4.setText("Date of Session");

        jLabel5.setText("Cost of Session");

        jLabel6.setText("IDC 10");

        jLabel7.setText("Diagnostic Code");

        btnAddSession.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAddSession.setText("Add Session");
        btnAddSession.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSessionActionPerformed(evt);
            }
        });

        cmbName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbNameActionPerformed(evt);
            }
        });

        cmbSname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSnameActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel8.setText("Time");

        cmbHour.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", " " }));
        cmbHour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbHourActionPerformed(evt);
            }
        });

        cmbMin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { ":00", " " }));
        cmbMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMinActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(lblHead, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(btnAddSession, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(67, 67, 67)
                                .addComponent(cmbName, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel6))
                                .addGap(76, 76, 76)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cmbHour, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cmbMin, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtCode, javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(txtCost, javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(dateCmb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmbSname, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtIDC, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 10, Short.MAX_VALUE)))))
                        .addGap(46, 46, 46))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblHead, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbSname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dateCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cmbHour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIDC)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCost)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCode)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddSession)
                    .addComponent(btnBack))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddSessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSessionActionPerformed
        if (val.wasentered(this.txtCode.getText())//validates the entered information useing the validate classes methoods
                && val.wasentered(this.txtCost.getText()) && val.isNumber(this.txtCost.getText(), true)//validates the entered information useing the validate classes methoods
                && val.wasentered(this.txtIDC.getText()) && val.wasentered(this.dateCmb.toString()) && !this.dateCmb.getDateFormatString().equals("")) {//validates the entered information useing the validate classes methoods
            int patID = ptn.getID(cmbName.getSelectedItem().toString(), cmbSname.getSelectedItem().toString());//gets the patients ID
            String Date = this.dateCmb.getDate().toString();//gets the date
            String datewithasmallD = DATE.formatDate(Date);//formats the date
            if (viewSession.update == false) {//if the static variable update is set to be true
                String insert = sql.InsertSession(patID, datewithasmallD, txtIDC.getText(), txtCost.getText(), txtCode.getText(), this.cmbMin.getSelectedItem() + "");//passes in varables to the SqlStatements methood
                try {
                    db.UpdateDatabase(insert);//updates the data base using the sql command
                } catch (SQLException ex) {//catches the updateing of the data base
                    Logger.getLogger(NewSession.class.getName()).log(Level.SEVERE, null, ex);//creates an exception for the try statement 
                }
            } else {
                this.btnAddSession.setText("Update Session");//sets the text of the lable 
                String update = sql.UpdateSession(patID, datewithasmallD, txtIDC.getText(), txtCost.getText(), txtCode.getText(), this.cmbMin.getSelectedItem() + "");//passes in varables to the SqlStatements methood
                try {
                    db.UpdateDatabase(update);//updates the data base using the sql command
                } catch (SQLException ex) {//catches the updateing of the data base
                    Logger.getLogger(NewSession.class.getName()).log(Level.SEVERE, null, ex);//creates an exception for the try statement 
                }
            }
            JOptionPane.showMessageDialog(null, "Modification Complete");//alerts the user that the update was sucsessfull
            this.hide();//closes this screen 
            new viewSession().setVisible(true);//sets the viewSession to visiable
        } else {
            JOptionPane.showMessageDialog(null, Validate.message);//alerts the user that the update was not sucsessfull
            Validate.message = "";//resets the error message
        }
    }//GEN-LAST:event_btnAddSessionActionPerformed

    private void cmbNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbNameActionPerformed
        DefaultComboBoxModel name = new DefaultComboBoxModel(ptn.getPossibleSurnames(cmbName.getSelectedItem() + ""));//Declare a Default Combo Box Model inoreder to populate a combobox
        this.cmbSname.setModel(name);//sets the combo box to the model created above
    }//GEN-LAST:event_cmbNameActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.hide();//closes this screen
        new viewSession().setVisible(true);//sets the viewSession to visiable
    }//GEN-LAST:event_btnBackActionPerformed

    private void cmbSnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSnameActionPerformed
        if (viewSession.update == false) { //if the static variable update is set to be False
        DefaultComboBoxModel name = new DefaultComboBoxModel(ptn.getPossibleFirstnames(cmbSname.getSelectedItem() + ""));//Declare a Default Combo Box Model inoreder to populate a combobox
        this.cmbName.setModel(name);//sets the combo box to the model created above
        }
    }//GEN-LAST:event_cmbSnameActionPerformed

    private void cmbHourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbHourActionPerformed
        DefaultComboBoxModel MIN = new DefaultComboBoxModel(pop.getMin(cmbHour.getSelectedItem() + ""));//Declare a Default Combo Box Model inoreder to populate a combobox
        this.cmbMin.setModel(MIN);//sets the combo box to the model created above
    }//GEN-LAST:event_cmbHourActionPerformed

    private void cmbMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbMinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewSession.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewSession.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewSession.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewSession.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewSession().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddSession;
    private javax.swing.JButton btnBack;
    private javax.swing.JComboBox<String> cmbHour;
    private javax.swing.JComboBox<String> cmbMin;
    private javax.swing.JComboBox<String> cmbName;
    private javax.swing.JComboBox<String> cmbSname;
    private com.toedter.calendar.JDateChooser dateCmb;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblHead;
    private javax.swing.JTextField txtCode;
    private javax.swing.JTextField txtCost;
    private javax.swing.JTextField txtIDC;
    // End of variables declaration//GEN-END:variables
}
